# Generated by Django 2.0.1 on 2018-03-01 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watchshopapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('short_description', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='watch_images/')),
                ('price', models.IntegerField(default=0)),
                ('watchshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watchshopapp.WatchShop')),
            ],
        ),
    ]
