# Generated by Django 2.0.1 on 2018-07-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchshopapp', '0003_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='image',
            field=models.ImageField(blank=True, upload_to='watch_images/'),
        ),
    ]
